syntax on
set expandtab
set tabstop=2
" set textwidth=79

" colorscheme lucius

" map CTRL-t <direction> to tab movement
map <C-t><left> :tabp<cr>
map <C-t><right> :tabn<cr>
map <C-t><up> :tabr<cr>
map <C-t><down> :tabl<cr>