execute pathogen#infect()
"autocmd vimenter * NERDTree
map <C-n> :NERDTreeToggle<CR>

syntax on
set background=dark
set number
colorscheme solarized
let g:syntastic_enable_perl_checker = 1

set expandtab
set tabstop=2
"set textwidth=79

highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/

" map CTRL-t <direction> to tab movement
map <C-t><left> :tabp<cr>
map <C-t><right> :tabn<cr>
map <C-t><up> :tabr<cr>
map <C-t><down> :tabl<cr>

if has('statusline')
        set laststatus=2
        " Broken down into easily includeable segments
        set statusline=%<%f\    " Filename
        set statusline+=%w%h%m%r " Options
        set statusline+=%{fugitive#statusline()} "  Git Hotness
        set statusline+=\ [%{&ff}/%Y]            " filetype
        set statusline+=\ [%{getcwd()}]          " current dir
        set statusline+=%#warningmsg#
        set statusline+=%{SyntasticStatuslineFlag()}
        set statusline+=%*
        let g:syntastic_enable_signs=1
        set statusline+=%=%-14.(%l,%c%V%)\ %p%%  " Right aligned file nav info
endif
